# Generated by Django 3.0.3 on 2020-02-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='task',
            field=models.ManyToManyField(related_name='task_tag', to='tasks.Task'),
        ),
    ]
