# Generated by Django 3.0.3 on 2020-02-11 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20200210_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='task',
        ),
        migrations.AddField(
            model_name='task',
            name='tag',
            field=models.ManyToManyField(related_name='tag_task', to='tasks.Tag', verbose_name='Tag for task'),
        ),
    ]
